### ISSUE TITLE
problems with shiny

### ISSUE THREAD

**Issue by ShinyFabio** [jokergoo/InteractiveComplexHeatmap#34]
Hello,
I'm using the package ComplexHeatMap in shiny and I was trying to figure out how to use your package. I'll give a small example of my code.

```r
heatmapind = reactive({
#a lot of reactive code#
ht=ComplexHeatmap::Heatmap(data)
ht = ComplexHeatmap::draw(ht)
return(ht)
)}
```

Now I didn't understand how to use your package with my reactive data `heatmapind()`.
 It's not clear to me how to use the render and the output functions. It's not like `renderPlot({})` and `plotOutput({})` functions, am I right?

**Comment by jokergoo** [comment]
Can  you show me more of your code?

Normally the interactive heatmap is not created by `renderPlot()` because it is a complex widget that contains several plots and outputs.

Have you seen this vignette? https://bioconductor.org/packages/devel/bioc/vignettes/InteractiveComplexHeatmap/inst/doc/shiny_dev.html

The function `renderInteractiveComplexHeatmap()` actually uses many `renderPlot()` and `renderUI()`, so basically you simply send your heatmap object to this function.

Or do you mean your matrix e.g. `data` is also dynamic (reactive) so your heatmap is also reactive?

**Comment by jokergoo** [comment]
Maybe this example helps you:

```r
library(ComplexHeatmap)
library(InteractiveComplexHeatmap)

ui = fluidPage(
    sliderInput("n", "Number of rows and columns", value = 10, min = 5, max = 50),
    actionButton("submit", "Submit"),
    htmlOutput("heatmap_output")
)

server = function(input, output, session) {
	observeEvent(input$submit, {
		n = input$n
		m = matrix(rnorm(n*n), n)
		ht=  Heatmap(m, column_title = paste0("A ", n, "x", n, " matrix"))
		InteractiveComplexHeatmapWidget(input, output, session, ht, output_id = "heatmap_output")
	})
}
shiny::shinyApp(ui, server)
```

**Comment by themasterpg** [comment]
With the second example I understood more or less how it works. I added a button to update the plot and now everything is working. Basically I thought that the sintax was similar for every item in shiny (so with `render*` I make the output and with `*Output` I print the output). Here it's a bit different. However I worked like in my previous example (so I have the Heatmap object  `heatmapind ()`. Then 
```
#in server
observeEvent(input$updateheat,{  #where updateheat is the button
   InteractiveComplexHeatmap::renderInteractiveComplexHeatmap(input, output, session, dataheat())
})
```
And finally printed it in the ui with:
`InteractiveComplexHeatmapOutput() #without anything inside the brackets. `

Still it's not perfectly clear to me but it works! I have just a question. I saw that in the `InteractiveComplexHeatmapOutput()` function is possible to split plots into two rows (with nrow=2), but doing this, the "box" that shows number when you click on a cell, is positioned in a third row (so first row heatmap, second row subheatmap and third row the "box"). Is it possible to shift the box next to the subheatmap? (so first row heatmap and second row subheatmap + box)
Thank you!

**Comment by jokergoo** [comment]
Yeah, I agree the name of the function starting with `render**` maybe is not a good idea... Maybe I can think of some other names... Maybe I call it `generateInteractiveComplexHeatmap()` or `InteractivateComplexHeatmap()`?

The implementation of `nrow=2` is very naive. If `nrow = 1`, the main heatmap and the sub-heatmap are set as `float:left` in CSS, and when `nrow = 2`, the two div blocks are just put one below the other.

Yes, this is a good comment! I will think about a flexible solution for this!

**Comment by themasterpg** [comment]
I'm glad that I helped. I have another suggestion for you. Maybe you can add an option that can order the annotations. In my App I can choose to cluster by row, by column or both. I have also the possibility to choose the column for the annotations (annotations in the row). Now if I choose to cluster by row, I can't order of annotations because the clustering. But if choose to not cluster by row, since the annotations are in the rows, I wanted to group them. The problem was that annotations and heatmap are not linked so if I group (i.e. order) them, they don't refer anymore to the corresponding heatmap cell. So to solve this I first sorted by the annotation column my data, than I make the heatmap and the annotation with the ordered data.
If can help you I used this code to order:
```

datasorted = reactive({
     
     req(data())   #my data
     seletannota = input$selectannot  #this is the column used for the annotation
    htdata = data()
     
     if(input$heatsort == TRUE){    #input$heatsort is simply a checkbox 
       htdata[do.call(order, htdata[as.character(seletannota[1])]), ]   #here I order my data by seletannota 
       
     } else{
       return(htdata)
     }
     
   })

```
I attach also my heatmaps to show you the difference.
![Senza titolo](https://user-images.githubusercontent.com/78078351/106451904-774f9980-6487-11eb-9df1-99d3bec2dfdb.jpg)
![ordered](https://user-images.githubusercontent.com/78078351/106451910-79195d00-6487-11eb-927b-4755be0b6400.jpg)
![cluster by row](https://user-images.githubusercontent.com/78078351/106451914-79b1f380-6487-11eb-97a0-6c11bba28738.jpg)

**Comment by jokergoo** [comment]
Hi, I think it is a thing of how to reorder the heatmap while not a problem for this shiny app. One thing that is important for interactive complex heatmap is before converting it interactive, the heatmap should be fixed, which means,  you cannot reorder or make any change of the heatmap in the shiny app. But you can do it before sending to e.g. `InteractiveComplexHeatmapWidget()`.

If I understood correctly, what you want is to first order the rows by "Province" and for the rows sharing a same level in Province, you still want to apply clustering? If so, maybe you can try the function `cluster_within_group()`?

By the way, in the new version, I add a new argument `layout` which provides two layouts for the heatmaps and output. For your case, you can set `layout = "1|23" so that the sub-heatmap box will be on the same row as the output box.

**Comment by ShinyFabio** [comment]
No my idea is to order the rows by "Provincia" but only if I don't cluster by row. I know that clustering rows will change all the rows order to make the dendrogram more readible so i don't want to change the order if I cluster. But if I don't cluster (always by row) I wanted to make cells "tidier" ordering by "Provincia". My problem was that annotations and heatmap are not linked so if I change thea order of the annotation cells, the order of heatmap cells doesnt' change together. I'm not asking you to solve this because I've already solved with the code of the previous comment. I'm just telling you this as a suggestion or simply as an help if you want to include this option.  In the images of my last comment:

- the "Clustered by row" image doesn't have any ordering. The only ordering is provided by the clustering and it's ok like this.
- the "Not ordered" image is still not orderd but also not clusterd by row, so the row order (of both heatmp and annotation) is given by my data. 
- the "Ordered" image is still not clusterd but here I ordered my data by row (by "Provincia") and then I made the heatmap. Doing this you can see that the annotations are orderd.

Now, since annotations and heatmap cells are not linked by a key (so they don't change together but they are two separated things) I had to order my data BEFORE everything (so before the annotation and heatmap making). If for example I order only the annotation, the heatmap cells order doesn't change so each annotation doesn't refer anymore to the correspondant cell value. I hope now I was more clear but however don't mind about that I've already solver the problem. It was just a suggestion (like maybe trying to link annotation and heatmap cells so they change together). 

However about the layout, i'm not sure but, if I remember correctly, with `InteractiveComplexHeatmapWidget` I had the same problem (that doesn't work with `ht()`) and I solved using instead `renderInteractiveComplexHeatmap`. But I think that I should move again to the "widget" function because I think that  `layout = "1|23"` doesn't work with the "render" function. Am I right?

**Comment by jokergoo** [comment]
>  i don't want to change the order if I cluster.

Why don't you want to change the order of `Provincia` when you do clustering on the heatmap? In ComplexHeatmap, the row annotations and heatmap are linked, which means, changing the order of either one will also automatically reorder the other.

In all your three heatmaps, the row annotations correspond correctly to the heatmap, for which the red always corresponds to AV*, purple to SA*, et al., no matter how you reorder the rows.

In the new version (the GitHub version), `renderInteractiveComplexHeatmap()` and `makeInteractiveComplexHeatmap()` are basically the same function, just with different function names.

I think it would be better if you also attach the code.
